### ISSUE TITLE
Question: How is this different from those 'awesome' lists on GitHub?

### ISSUE THREAD

**Issue by pablodenadai** [vic317yeh/One-Click-to-Be-Pro#8]
https://github.com/sindresorhus/awesome

**Comment by mii9000** [comment]
I guess this is more like a list of one-hit ko of topics :hand:

**Comment by btn0s** [comment]
It's not. Doesn't have to be. :+1:

**Comment by aplanas** [comment]
I hope that remains to the idea of one single link for topic

**Comment by vicoyeh** [comment]
@ghpabs The link your shared is AWESOME! I didn't know that list exists before, so thanks for sharing it here 👍 

I often found it difficult to start learning new tech because there are just too many resources available online. I thought it would be nice to have a list where each topic only has one link and is recommended by someone who has experience with the technology. 

I first created the list to help underclassmen in my college to get started in doing side projects. And I have ABSOLUTELY no ideas how this repo got so popular. In the future, this list will be maintained in the same way. Quoting @Ibrahim-Islam, it is going to be "a list of one-hit ko of topics" 🎯
